#!/usr/bin/env python3
"""Extract Inter glyph outlines for the deterministic brand PNG renderer.

Reads the locally hosted Inter woff2 files (site-assets/fonts, SIL OFL 1.1)
and writes scripts/brand-type.mjs: printable-ASCII outlines plus advance
widths for the two weights the brand images use. Run from the repository
root whenever the font files change:

    python scripts/tools/extract-brand-type.py

Requires: fonttools + brotli (pip install fonttools brotli).
The output is plain data; the site build never loads the fonts itself.
"""

import json
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

REPO = Path(__file__).resolve().parents[2]
WEIGHTS = {
    800: "inter-latin-800-normal.woff2",
    700: "inter-latin-700-normal.woff2",
    500: "inter-latin-500-normal.woff2",
}
FIRST, LAST = 0x20, 0x7E  # printable ASCII


def extract(weight: int, filename: str) -> dict:
    font = TTFont(REPO / "site-assets" / "fonts" / filename)
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    glyphs = {}
    for code in range(FIRST, LAST + 1):
        char = chr(code)
        name = cmap.get(ord(char))
        if name is None:
            print(f"  weight {weight}: no glyph for {char!r}, skipped", file=sys.stderr)
            continue
        glyph = glyph_set[name]
        pen = SVGPathPen(glyph_set)
        glyph.draw(pen)
        # Spacing-only glyphs (space) have no outline but must keep their
        # advance width for text layout.
        glyphs[char] = {"w": glyph.width, "d": pen.getCommands()}
    return {"upem": font["head"].unitsPerEm, "glyphs": glyphs}


def main() -> None:
    data = {}
    upems = set()
    for weight, filename in WEIGHTS.items():
        table = extract(weight, filename)
        upems.add(table["upem"])
        data[str(weight)] = table["glyphs"]
    assert len(upems) == 1, f"mixed unitsPerEm across weights: {upems}"
    body = json.dumps(data, ensure_ascii=True, separators=(",", ":"))
    out = REPO / "scripts" / "brand-type.mjs"
    out.write_text(
        "// GENERATED by scripts/tools/extract-brand-type.py -- do not edit by hand.\n"
        "// Inter (SIL OFL 1.1) printable-ASCII outlines in font units for the\n"
        "// deterministic brand PNG renderer (scripts/brand-kit.mjs).\n"
        f"export const UPEM = {upems.pop()};\n"
        f"export const GLYPHS = {body};\n",
        encoding="ascii",
    )
    print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
